version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sdle
      POSTGRES_PASSWORD: sdle
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: sdle@feup.pt
      PGADMIN_DEFAULT_PASSWORD: pg!password
    ports:
      - "4321:80"
    depends_on:
      - postgres

